Closes #995. Add mod lord_bricks, add 2 types of bricks (and their crafts)
lord-server/lord pull request #1002
Opened 2023-03-04 02:08 UTC by Doloment

See #995 for images

2023-05-31 22:56 UTC, alek13 requested changes

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/init.lua
> +minetest.register_craftitem("clay_types:chamotte_clay_lump", {
лишний раз слово "clay", название становится слишком длинным.
лучше использовать `clay_types:chamotte_lump`.

например, `wool:red`, но не `wool:red_wool`

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/init.lua
> +minetest.register_node("clay_types:chamotte_clay_block_raw", {
ну и в остальных тоже

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/init.lua
> +minetest.register_craftitem("clay_types:mordor_clay_lump", {
и с мордорскими названиями

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/locale/clay_types.ru.tr
> +Outer Dried Mordor Clay Block Stair=Ступень из Высушенного Блока Мордорской Глины (Внешний Угол)
перевод строки в конце забыл.

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/mod.conf
> +depends = lord_overwrites_mtg_default, stairs
перевод строки

2023-05-31 22:56 UTC, alek13 commented on mods/lord/lord_bricks/locale/lord_bricks.ru.tr
> +Outer Mordor Clay Block Stair=Ступень из Блока из Мордорской Глины (Внешний Угол)
перевод строки

2023-05-31 22:56 UTC, alek13 commented on mods/lord/lord_bricks/mod.conf
> +depends = lord_overwrites_mtg_default, stairs
перевод строки

2023-05-31 22:56 UTC, alek13 commented on mods/lord/clay_types/init.lua
> +minetest.register_craft({
если это единственное отличие (похоже остальное у этих глин/блоков/кирпичей одинаково), может стоит подумать об объединении в общую функцию регистрации.

2023-06-01 08:33 UTC, Doloment commented on mods/lord/clay_types/init.lua
> +minetest.register_craft({
Я об этом тебе и говорил, когда делал мод, а ты "Да че там API зачем делать, просто перенеси и всё", поэтому я так делать не стал.

2023-06-01 08:55 UTC, Doloment commented on mods/lord/clay_types/init.lua
> +minetest.register_craftitem("clay_types:mordor_clay_lump", {
Мордорские оставлю как есть, чтобы был акцент на том что они из глины

2023-06-01 09:23 UTC, Doloment commented on mods/lord/clay_types/init.lua
> +minetest.register_craft({
Крч, я думаю не в этот раз

2023-06-03 10:56 UTC, alek13 commented on mods/lord/clay_types/init.lua
> +minetest.register_craft({
> Я об этом тебе и говорил, когда делал мод, а ты "Да че там API зачем делать, просто перенеси и всё", поэтому я так делать не стал.

Так а при чём тут API. Я про локальную функцию -- дабы ихбежать дубляжа кода.
Но на данный момент не особо критично. Вот когда будем сюда ещё что-то добавлять -- станет уже критично.

2023-06-03 11:17 UTC, merged