Refactor lord_bows
lord-server/lord pull request #1303
Opened 2024-04-28 13:22 UTC by Doloment

- Отрефакторил lord_bows под новый стиль
- Добавил поддержу создания других луков и снарядов (стрел)
- Поменял механизм зарядки лука: теперь скорость выпускаемого снаряда зависит не от стадии заряда лука, а от того, насколько долго он заряжался (в процентах от максимального времени заряда)
- Добавил переводы
- Добавил док-блоки
- Исправлена проблема с прочностью лука
- Поменял поведение стрел при окончании их жизни: они выбрасываются как айтемы, а не исчезают
- Поднятие стрелы теперь на ЛКМ, а не на ПКМ
- Добавил частицы, показывающие траекторию полёта стрелы
![image](https://github.com/lord-server/lord/assets/22934348/45c9c50d-e51c-4f84-a2fb-0eb969e76b94)

2024-04-28 21:10 UTC, alek13 requested changes
В целом очень круто, спасибо.
Отписал по мелочам.
Дотошно логику не проверял на какие-то упущения в силу человеческого фактора, т.к. это пока в экспериментальном и будем ещё тщательно тестить всю механику.

2024-04-28 21:10 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/bows/behavior/mechanics_throwing.lua
> +				return name
![image](https://github.com/lord-server/lord/assets/1972329/05117d10-1811-4813-8073-de2b4f3c05ad)
это из-за того, что у массива, где хранятся луки не прописан правильно тип.
иправляется простым:
```lua
local bows = {
	--- @type table<string,тут-подставить-тип-который-определить-отдельно>
	registered_bows        = {},
```

2024-04-28 21:10 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/bows/behavior/mechanics_throwing.lua
> +--- @param bow_stages table              a table {stages = {[0] = <item> ...}, charging_time = {[0] = <seconds> ...}}
тоже лучше определить отдельный тип наподобие этого https://github.com/lord-server/lord/blob/dev/mods/lord/Blocks/lord_trees/src/tree/Generator.lua#L208-L211

2024-04-28 21:10 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/lord_bows.lua
> +lord_bows.get_projectiles = api.get_projectiles
Эти 2 строки лишние, т.к. в 9 строке ты весь api присваеваешь.
Либо их нужно перенести внутрь `register_api()`, чтобы не весь локальный api отдавать наружу в глобальный api.
Посмотри как лучше

2024-04-29 03:24 UTC, Doloment commented on mods/lord/_experimental/lord_bows/src/bows/behavior/entity_projectiles.lua
> +--- @param projectile LuaEntity  projectile entity
Эти функции вызываются внутри коллбэков, указанных в регистрации энтити. Туда, согласно документации передаётся таблица `luaentity` как `self`, оттуда оно распространяется во все эти подфункции, так что это `LuaEntity`
![image](https://github.com/lord-server/lord/assets/22934348/95e7613b-a18e-4180-8896-6b4e8a4bdec0)

2024-04-29 11:49 UTC, alek13 requested changes

2024-04-29 11:49 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/bows/api.lua
> +	--- @type table<bows.BowRegistration>
не указал тип ключа:
```suggestion
	--- @type table<string,bows.BowRegistration>
```
https://emmylua.github.io/annotations/dict.html

2024-04-29 11:49 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/bows/behavior/entity_projectiles.lua
> +local pi     = math.pi
ага, так, только в самой первой строке, а потом уже ижут всякие `require()` и `local projectiles  = {}` уже после

2024-04-29 11:49 UTC, alek13 commented on mods/lord/_experimental/lord_bows/src/bows/api.lua
> +	--- @type table<bows.BowRegistration>
в остальных местах тоже глянь

2024-04-29 12:21 UTC, merged