Add lord_scrolls:scroll
lord-server/lord pull request #1328
Opened 2024-05-14 01:07 UTC by vladtcvs

**Описание PR:**

Добавил свиток - аналог книги, но редактировать может кто угодно.

**Рекомендации к тесту:**

1. Проверить подсветку наименования книги при просмотре через инвентарь
2. Проверить сохранение контента
3. Проверить доступ к редактированию разными людьми

2024-05-14 01:07 UTC, vladtcvs commented
TODO: надо красивую иконку

2024-05-16 14:12 UTC, Doloment requested changes
Кодстайл:
- В однострочных таблицах следует добавлять пробелы после открывающей фигурной скобки и перед закрывающей
- Следует выполнять alignment док-блоков и выражений с присваиванием

2024-05-25 10:20 UTC, vladtcvs commented on mods/lord/Tools/lord_books/scroll.lua
> +local SL = minetest.get_translator("lord_books")
fixed

2024-05-25 10:20 UTC, vladtcvs commented on mods/lord/Tools/lord_books/init.lua
> +})
fixes

2024-05-25 10:21 UTC, vladtcvs commented on mods/lord/Tools/lord_books/scroll.lua
> +---comment
fixed

2024-05-25 10:22 UTC, vladtcvs commented on mods/lord/Tools/lord_books/scroll.lua
> +	-- Store the wield index in case the user accidentally switches before the formspec is shown
fixed

2024-05-25 11:30 UTC, Doloment requested changes

2024-05-25 11:30 UTC, Doloment commented on mods/lord/Tools/lord_books/scroll.lua
> +---@return string formspec
```suggestion
---@param  title  string   title of the scroll
---@param  text   string   content of the book
---@return        string formspec
```

2024-05-25 11:30 UTC, Doloment commented on mods/lord/Tools/lord_books/scroll.lua
> +---@return ObjectRef player's itemstack nothing consumed
```suggestion
---@param  itemstack ObjectRef player's itemstack
---@param  user      Player    player
---@return           ObjectRef player's itemstack nothing consumed
```

2024-05-25 11:30 UTC, Doloment commented on mods/lord/Tools/lord_books/scroll.lua
> +	groups = {book = 1, flammable = 3},
```suggestion
	groups = { book = 1, flammable = 3 },
```

2024-05-25 11:30 UTC, Doloment commented on mods/lord/Tools/lord_books/scroll.lua
> +	book_writers[player_name] = {wield_index = user:get_wield_index()}
```suggestion
	book_writers[player_name] = { wield_index = user:get_wield_index() }
```

2024-05-25 15:52 UTC, Doloment approved these changes

2024-05-25 17:28 UTC, merged