Fix throwing engine
lord-server/lord pull request #292
Opened 2021-04-18 21:28 UTC by vladtcvs

Аналитический расчет пересечения пути полета стрелы с collision box вместо проверки того, что набор точек на пути лежит внутри collision box

2021-04-20 01:04 UTC, alek13 commented
при выстреле в нижнюю половину игрока-соперника стрелы пролетают насквозь

2021-04-20 01:04 UTC, alek13 commented
при выстреле игрока-орка в моба-орка, моб не агрится

2021-04-20 01:17 UTC, alek13 commented
игрок в игрока стрелами с Ателасом -3:
```
2021-04-20 04:14:30: ACTION[Server]: Alek [127.0.0.1] joins game. List of players: Alek
2021-04-20 04:15:01: ACTION[Server]: Orc [127.0.0.1] joins game. List of players: Alek Orc
2021-04-20 04:15:12: ACTION[Server]: Alek uses lottthrowing:bow_wood_mallorn, pointing at [object 8]
2021-04-20 04:15:13: ACTION[Server]: player Alek (id=1, hp=20) punched player Orc (id=8, hp=18), damage=2
2021-04-20 04:15:13: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback luaentity_Step(): .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:458: attempt to index local 'pos' (a nil value)
2021-04-20 04:15:13: ERROR[Main]: stack traceback:
2021-04-20 04:15:13: ERROR[Main]:       .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:458: in function 'inside_owner'
2021-04-20 04:15:13: ERROR[Main]:       .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:545: in function <.../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:473>
2021-04-20 04:15:13: ACTION[Server]: Alek leaves game. List of players: 
2021-04-20 04:15:13: ACTION[Server]: Orc leaves game. List of players: 
2021-04-20 04:15:13: ACTION[Main]: Server: Shutting down
```

2021-04-20 12:30 UTC, alek13 requested changes

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +function throwing:shoot(owner, owner_type, arrow_name, pos, dir, distance)
У метательных топоров не верный вызов этого метода
```
2021-04-20 15:05:49: ACTION[Server]: Orc uses arrows:axe_steel, pointing at [object 5]
2021-04-20 15:05:49: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'arrows' in callback item_OnUse(): ...netest/bin/../games/lord/mods/lord/throwing/init.lua:47: attempt to index local 'dir' (a number value)
2021-04-20 15:05:49: ERROR[Main]: stack traceback:
2021-04-20 15:05:49: ERROR[Main]:       ...netest/bin/../games/lord/mods/lord/throwing/init.lua:47: in function 'shoot'
2021-04-20 15:05:49: ERROR[Main]:       ...minetest/bin/../games/lord/mods/lord/arrows/init.lua:37: in function <...minetest/bin/../games/lord/mods/lord/arrows/init.lua:32>
2021-04-20 15:05:49: ACTION[Server]: Alek leaves game. List of players: 
2021-04-20 15:05:49: ACTION[Server]: Orc leaves game. List of players: 
2021-04-20 15:05:49: ACTION[Main]: Server: Shutting down
```
вызов тут:
`mods/lord/arrows/init.lua:37`

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +		   arrow.owner.z == math.floor(pos.z) then
ой, долго сначала подумал, что отформатировано неверно...
давай `then` на другую строчку перенесём

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +--	minetest.log(cbox[1].." "..cbox[2].." "..cbox[3].." "..cbox[4].." "..cbox[5].." "..cbox[6])
лишнее

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +--	minetest.log("found "..tostring(cbox))
лишнее

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +--		minetest.log("owner = "..arrow.owner.x.." "..arrow.owner.y.." "..arrow.owner.z)
лишнее

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +--				minetest.log("cb "..tostring(collision_box[0]).." pos "..tostring(ppos.x))
лишнее

2021-04-20 12:30 UTC, alek13 commented on mods/lord/throwing/init.lua
> +--			minetest.log("target = "..target.." archer "..archer)
лишнее

2021-04-20 12:33 UTC, alek13 commented
> игрок в игрока стрелами с Ателасом -3:
> 
> ```
> 2021-04-20 04:14:30: ACTION[Server]: Alek [127.0.0.1] joins game. List of players: Alek
> 2021-04-20 04:15:01: ACTION[Server]: Orc [127.0.0.1] joins game. List of players: Alek Orc
> 2021-04-20 04:15:12: ACTION[Server]: Alek uses lottthrowing:bow_wood_mallorn, pointing at [object 8]
> 2021-04-20 04:15:13: ACTION[Server]: player Alek (id=1, hp=20) punched player Orc (id=8, hp=18), damage=2
> 2021-04-20 04:15:13: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback luaentity_Step(): .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:458: attempt to index local 'pos' (a nil value)
> 2021-04-20 04:15:13: ERROR[Main]: stack traceback:
> 2021-04-20 04:15:13: ERROR[Main]:       .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:458: in function 'inside_owner'
> 2021-04-20 04:15:13: ERROR[Main]:       .../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:545: in function <.../alek13/.minetest/games/lord/mods/lord/throwing/init.lua:473>
> 2021-04-20 04:15:13: ACTION[Server]: Alek leaves game. List of players: 
> 2021-04-20 04:15:13: ACTION[Server]: Orc leaves game. List of players: 
> 2021-04-20 04:15:13: ACTION[Main]: Server: Shutting down
> ```
> 
>     * тоже самое при обычных стрелах
> 
>     * тоже самое при выстреле в моба
> 
> 
> тестил на `5.3`
> 
> P.S.: таже ошибка: [CasimirKaPazi/Voxelgarden#62 (comment)](https://github.com/CasimirKaPazi/Voxelgarden/issues/62#issuecomment-656854242) .
> Нам бы на `mobs_redo` перелезть и желательно без его изменений

это на `5.1.1` не воспроизводится, вынесу в отдельный баг на `5.3`

2021-04-20 15:41 UTC, vladtcvs commented on mods/_lott/lottmobs/elves.lua
> +		shoot_offset         = 0.7,
> Нам бы на `mobs_redo` перелезть и желательно без его изменений

стреляющие мобы  эльфы, орки, назгулы, балроги - они должны вызывать наш throwing

2021-04-24 15:56 UTC, alek13 commented on mods/_lott/lottthrowing/init.lua
> +minetest.register_node("lottthrowing:arrownode", {
эту ноду нужно в `lord/throwing` перенести

2021-04-24 15:57 UTC, alek13 commented on mods/_lott/lottmobs/elves.lua
> +		shoot_offset         = 0.7,
на `0.75`

2021-04-24 16:14 UTC, merged