Dynamic Spawn
lord-server/lord pull request #330
Opened 2021-05-07 16:51 UTC by Doloment

Related to #311

Я, конечно, протестил, но нужно еще. Вдруг где-то есть что-то, что работает не так.

Так. Что изменено/добавлено:

- Если `dynamic_spawn` в конфиге `= true`, то `/spawn` перемещает игрока на "родной" спаун - соответствующий его расе. Если координаты спавна не заданы в конфиге - берутся координаты общего спауна. Если и их нет - "Переместиться не удалось" в чат + соответствующий action в лог (именно action, а не error, ибо ошибка выводится и в чат игроку, а это "спойлер")

- Добавлена админская команда `/choose_spawn <race>`, которая перемещает игрока, использовавшего её, на спаун определённой расы

- После выбора расы, пола и скина игрок перемещается на родной спаун. Работает даже после второго шанса - не стал это фиксить

- **Новые спауны затрагивают мод `beds`, что нужно будет учесть при его обновлении**

Новые поддерживаемые настройки в конфиге: 
`dynamic_spawn = bool` - Включает/выключает динамический спаун
`common_spawn_pos = x, y, z` - координаты Общего Спауна
`hall_of_life_pos = x, y, z` - координаты Зала Жизни
`orc_spawn_pos = x, y, z` - координаты Спауна Орков
`man_spawn_pos = x, y, z` - координаты Спауна Людей
`dwarf_spawn_pos = x, y, z` - координаты Спауна Гномов
`hobbit_spawn_pos = x, y, z` - координаты Спауна Хоббитов
`elf_spawn_pos = x, y, z` - координаты Спауна Эльфов

2021-05-09 20:34 UTC, alek13 requested changes

2021-05-09 20:34 UTC, alek13 commented on mods/lord/spawn/init.lua
> +minetest.register_chatcommand("choose_spawn", {
давай переименуем в `spawn_to`

2021-05-09 20:34 UTC, alek13 commented on mods/lord/spawn/init.lua
> +--[[minetest.register_chatcommand("spawn", {
мёртвый код. нужно грохнуть

2021-05-09 20:34 UTC, alek13 commented on mods/lord/spawn/init.lua
> +--[[minetest.register_on_respawnplayer(function(obj)
мёртвый код, нужно грохнуть

2021-05-10 05:52 UTC, Doloment commented on mods/_minetest_game/beds/functions.lua
> +	if spawn.check_spawnpoint(races.get_race(name).."_spawn_pos") then
Это необходимо для корректного респауна игрока. На самом деле, могу попробовать переместить это в spawn

2021-05-10 06:06 UTC, Doloment commented on mods/lord/spawn/depends.txt
> +lord_classes
В spawn используется races.get_race из lord_classes.

Проверил: всё робит, даже если не указана зависимость.

2021-05-10 06:40 UTC, Doloment commented on mods/lord/spawn/depends.txt
> +lord_classes
Убрал вовсе, раз уж и так всё ок

2021-05-10 06:40 UTC, Doloment commented on mods/_minetest_game/beds/functions.lua
> +	if spawn.check_spawnpoint(races.get_race(name).."_spawn_pos") then
Переместил в spawn

2021-05-10 12:07 UTC, alek13 commented on mods/_minetest_game/beds/functions.lua
> +	if spawn.check_spawnpoint(races.get_race(name).."_spawn_pos") then
а зачем ? респаун у кровати пусть остаётся

2021-05-10 12:10 UTC, Doloment commented on mods/_minetest_game/beds/functions.lua
> +	if spawn.check_spawnpoint(races.get_race(name).."_spawn_pos") then
В кровати осталось то, что было с самого начала. Остальное переместил в spawn

2021-05-10 12:13 UTC, alek13 commented on mods/_minetest_game/beds/functions.lua
> +	if spawn.check_spawnpoint(races.get_race(name).."_spawn_pos") then
Это понятно. Просто теперь респаун у кровати не работает ?

2021-05-10 20:04 UTC, alek13 approved these changes

2021-05-10 20:16 UTC, merged