Fix skins
lord-server/lord pull request #338
Opened 2021-05-11 02:54 UTC by vladtcvs

Related: #339 
![image](https://user-images.githubusercontent.com/1972329/117833302-e4d94600-b27e-11eb-99e4-cb56660ce2b2.png)

2021-05-12 09:25 UTC, vladtcvs commented on mods/_lott/lottarmor/depends.txt
> +
fixed

2021-05-12 09:25 UTC, vladtcvs commented on mods/_lott/lottarmor/armor.lua
> +
fixed

2021-05-12 09:26 UTC, vladtcvs commented on mods/_lott/lottarmor/multiskin.lua
> +	elseif skin_mod == "lord" then
Код внешнего вида, брони и одежды все равно нуждается в переработке

2021-05-13 00:07 UTC, alek13 requested changes

2021-05-13 00:07 UTC, alek13 commented on mods/_lott/lottarmor/armor.lua
> +
договорились:
 - вынести всё-таки в наш `lord_classes`
 - создать задачи на:
   - обновление `lottarmor` из `LOTT` в последний раз
   - перенос `lottarmor` из папки `_lott` в папку `lord`
   - рефакторинг: резделение брони и формы инвенторя на разные моды/папки

2021-08-24 21:28 UTC, alek13 commented on mods/_lott/lottarmor/armor.lua
> +
рефакторинг пока отложили, вливаем скины

2021-08-24 21:31 UTC, merged