Build dependency graph
lord-server/lord pull request #363
Opened 2021-05-21 22:16 UTC by vladtcvs

2021-05-26 11:53 UTC, alek13 commented
Обсудили в [Discord](https://www.discord.gg/BabPfm6xtD): нужно добавить описание по установке требуемых пакетов и использовании в [`development.md`](https://github.com/lord-server/lord/blob/master/development.md) (Добавить там раздел _"Дополнительные утилиты"_)

2021-05-26 11:54 UTC, alek13 commented
Файл `deps.pdf` нужно убрать из коммита и добавить его в `.gitignore`

2022-01-09 13:30 UTC, weqqr requested changes
А почему `.gitignore` пустой?

2022-01-09 13:30 UTC, weqqr commented on development.md
> +   python3 -m pip install graphviz
```suggestion
   `python3 -m pip install graphviz`
```

2022-01-09 14:52 UTC, vladtcvs commented on development.md
> +   python3 -m pip install graphviz
Поправил

2022-01-09 14:54 UTC, weqqr approved these changes

2022-01-09 14:55 UTC, merged