Добавлена команда /dice для чата
lord-server/lord pull request #364
Opened 2021-06-09 16:37 UTC by ptah-alexs

2021-06-09 17:30 UTC, alek13 requested changes

2021-06-09 17:30 UTC, alek13 commented on mods/_various/simple_chat_dice/init.lua
> +    description = "print out random number",
нужно добавить перевод (стандартным встроенным переводчиком)

2021-06-09 18:50 UTC, ptah-alexs commented on mods/_various/simple_chat_dice/init.lua
> +    description = "print out random number",
Честно я не понимаю как этот перевод работает

2021-06-09 18:52 UTC, alek13 commented on mods/_various/simple_chat_dice/init.lua
> +    description = "print out random number",
можно в качестве примера посмотреть тут:
https://github.com/minetest/minetest_game/tree/master/mods/beds

2021-06-09 20:03 UTC, ptah-alexs commented on mods/_various/simple_chat_dice/init.lua
> +    description = "print out random number",
В общем сделал

2021-06-09 23:04 UTC, alek13 requested changes
Сам мод нужно в папку `mods/lord` закинуть.
см. [`mods/readme.md`](https://github.com/lord-server/lord/blob/master/mods/readme.md)

и папку мода переименовать `simple_chat_dice` -> `dice`

2021-06-09 23:04 UTC, alek13 commented on mods/_various/simple_chat_dice/mod.conf
> +description = Minetest Game mod: dice
это не из MTG.
тут должно быть что-то вроде:
```suggestion
description = Adds `/dice` chat command for printing random numbers
```

2021-06-10 02:40 UTC, ptah-alexs commented on mods/_various/simple_chat_dice/init.lua
> +		local t = 6
Тут я через редактор гитхаба правил, вот и вышла такая неприятность

2021-06-10 11:52 UTC, ptah-alexs commented
возможно стоит добавить /dice-series для генерации нескольких бросков сразу?

2021-06-10 12:06 UTC, kevicky9 commented
Да не надо уж

2021-06-10 13:12 UTC, alek13 commented on mods/_various/simple_chat_dice/init.lua
> +		local t = 6
только пробелы остались, а у нас табы
```
indent_style = tab
```

2021-06-10 13:48 UTC, alek13 requested changes
команду ещё нужно протестить локально.
похоже она нерабочая.
пробелы на табы заменить

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +    func = function(name, param_num)
```suggestion
    func = function(name, param)
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +        if (param_num ~= "") then
```suggestion
        if (param ~= "") then
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +            local t1 = tonumber(param_num)
```suggestion
            local param_num = tonumber(param)
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +            if (t1 ~= nil) then
```suggestion
            if (param_num ~= nil) then
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +        local t = 6
```suggestion
        local max_num = 6
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +                t = t1
```suggestion
                max_num = param_num
```

2021-06-10 13:48 UTC, alek13 commented on mods/lord/dice/init.lua
> +    max_num = S("<MAX_NUM>"),
а это что ? см. [Chat command definition](https://minetest.gitlab.io/minetest/definition-tables.html#chat-command-definition)

2021-06-11 16:41 UTC, alek13 commented on mods/lord/dice/init.lua
> +    max_num = S("<MAX_NUM>"),
это вопрос непосредствнно к строке
```lua
    max_num = S("<MAX_NUM>"),
```

2021-06-11 16:42 UTC, alek13 commented on mods/lord/dice/init.lua
> +    max_num = S("<MAX_NUM>"),
аа, пардон, уже поправлено

2021-06-11 16:43 UTC, alek13 approved these changes

2021-06-11 16:43 UTC, merged