Periodic damage hobbits in certain area
lord-server/lord pull request #368
Opened 2021-06-12 07:42 UTC by Doloment

Связано с #310

Это только HP. В закомментированных строках есть заготовка для глаза.

2021-06-17 21:25 UTC, alek13 requested changes

2021-06-17 21:25 UTC, alek13 commented on mods/lord/lord_classes/effects.lua
> +--[[local function sauron_eye() --заготовка на глаз
закоментированный и нерабочий код лучше не коммитить - считается плохим тоном

2021-06-17 21:25 UTC, alek13 commented on mods/lord/lord_classes/effects.lua
> +local areaId          = tonumber(minetest.settings:get("sauron_curse_area"))
`areaId` -> `area_id`

2021-06-17 21:25 UTC, alek13 commented on mods/lord/lord_classes/effects.lua
> +minetest.register_globalstep(check_player_pos)
в конце всегда должен присутствовать перевод строки

2021-06-17 21:25 UTC, alek13 commented on mods/lord/lord_classes/effects.lua
> +            player:set_hp(player:get_hp()-2)
```suggestion
            player:set_hp(player:get_hp() - 2)
```

2021-06-18 00:07 UTC, alek13 commented
тут тоже сообщение к коммиту бы поменять:
```bash
git commit --amend -m 'Periodic damage hobbits in certain area. Closes #310'
```

2021-06-18 06:10 UTC, kevicky9 commented on mods/lord/lord_classes/effects.lua
> +local areaId          = tonumber(minetest.settings:get("sauron_curse_area"))
А почему именно такой стиль названия переменных?

2021-06-23 12:00 UTC, alek13 approved these changes

2021-06-23 12:00 UTC, merged