fix #312 Сброс скорости после сна
lord-server/lord pull request #429
Opened 2021-09-05 18:13 UTC by ptah-alexs

2021-09-06 12:40 UTC, alek13 commented
афектит на #269
лучше обновить полностью мод, обноляем до 2c9733ac4593e85cf27a44ad498f52b97499594e (5.4)

2021-09-06 13:20 UTC, ptah-alexs commented
В апстриме, кстати, этот баг [исправлен](https://github.com/minetest/minetest_game/blob/953fcfe09e0e258600dd22b8cd1ee1ab53bd1151/mods/beds/functions.lua#L117).

2021-09-06 13:54 UTC, alek13 commented
да, поэтому и говорю, что лучше сразу весь MTG/beds обновить

2021-09-06 14:36 UTC, ptah-alexs commented
тогда PR закрыть нужно?

2021-09-06 15:16 UTC, alek13 commented
ну можешь в этом же обновить и заодно пометить, что этим обновлением и этот баг исправлен

2021-11-27 22:18 UTC, alek13 requested changes
ждём правок

2021-11-30 22:39 UTC, weqqr approved these changes
✔ Работает

Ждём обновления до 5.4, на версиях старше крашится

Конец init.lua не совсем совпадает с MTG, но это не критично.
```diff
diff -r mods/_minetest_game/beds/init.lua ../minetest_game/mods/beds/init.lua
21,25c21,26
< -- load files
< dofile(modpath.."/functions.lua")
< dofile(modpath.."/api.lua")
< dofile(modpath.."/beds.lua")
< dofile(modpath.."/spawns.lua")
---
> -- Load files
>
> dofile(modpath .. "/functions.lua")
> dofile(modpath .. "/api.lua")
> dofile(modpath .. "/beds.lua")
> dofile(modpath .. "/spawns.lua")
```

2021-11-30 22:39 UTC, weqqr commented on mods/_minetest_game/beds/locale/beds.ru.tr
> +You have to stop moving before going to bed!=
Переводы есть в апстриме, после перехода на сабмодули появятся

2021-11-30 22:39 UTC, weqqr commented on mods/_minetest_game/beds/beds.lua
> +		{"wool:white", "wool:white", "wool:white"},
Рецепт изменился, но я думаю никто не расстроится

2021-11-30 22:39 UTC, weqqr commented on mods/_minetest_game/beds/functions.lua
> +		if vector.length(player:get_velocity()) > 0.001 then
`player:get_velocity()` работает начиная с 5.4

2021-12-02 05:21 UTC, ptah-alexs commented on mods/_minetest_game/beds/functions.lua
> +		if vector.length(player:get_velocity()) > 0.001 then
Мы же на 5.4 переходим, так что всё норм, разве нет?

2021-12-02 10:15 UTC, weqqr commented on mods/_minetest_game/beds/functions.lua
> +		if vector.length(player:get_velocity()) > 0.001 then
Да, всё норм.

2021-12-02 10:17 UTC, merged