Mod Lamps
lord-server/lord pull request #465
Opened 2021-10-29 20:05 UTC by VanicGame

Пока что только две лампы - золотая и бронзовая. Их два вида - потолочные и напольные. Потолочные имеют цепочку:
![screenshot_20211029_221232](https://user-images.githubusercontent.com/82447582/139495218-f61ac9fc-9c86-4753-bb5e-4859a4e86ead.png)
Есть крафты:
![screenshot_20211029_230405](https://user-images.githubusercontent.com/82447582/139495264-6bfa4eee-6eee-4614-9acc-4c2e6e4afbfb.png)
Локализация через встроенный локализатор.
Изображения оптимайзером **не прогнаны**.

2021-11-02 01:53 UTC, vladtcvs requested changes
Нужно пройтись оптимизатором по текстурам

2021-11-02 01:53 UTC, vladtcvs commented on mods/lord/lamps/init.lua
> +        minetest.item_place_node(itemstack, placer, pointed_thing, 0)
отступы

2021-11-02 01:53 UTC, vladtcvs commented on mods/lord/lamps/init.lua
> +      if pointed_thing.above.y ~= pointed_thing.under.y-1 then
здесь наверно имеет смысл добавить комментарий, описывающий логику сравнения, чтобы потом не забыть

2021-11-02 01:53 UTC, vladtcvs commented on mods/lord/lamps/locale/lamps.ru.tr
> +Gold candle lamp=Золотая свечная лампа
возможно лучше не свечная лампа, а лампа со свечой.

2021-11-04 17:10 UTC, vladtcvs approved these changes

2021-11-05 14:15 UTC, alek13 approved these changes

2021-11-05 14:16 UTC, merged