Сохранение расы, пола и скина в базе
lord-server/lord pull request #466
Opened 2021-10-30 16:59 UTC by vladtcvs

Для хранения расы, пола и скина используется метаданные игрока, созраняемые в базе.

Также в lottpotions и hbhunger были вставлены проверки, чтобы не падали

2021-11-04 19:16 UTC, alek13 commented
договорились разнести:
 - правки багов в `_lott/lottpotion` в отдельный PR
 - правки багов в `_various/hud_modpack/hbhunger` в отдельный PR
 - сохранение в базу в отдельный PR

2022-12-16 18:05 UTC, alek13 requested changes
Вцелом, LGTM. Нужна только небольшая правка по неймингу

2022-12-16 20:08 UTC, weqqr reviewed
Совместимость со старым форматом мешает читаемости, может лучше сделать скрипт для переноса существующих данных и убрать легаси код?

2022-12-27 10:01 UTC, vladtcvs commented on mods/lord/lord_classes/init.lua
> +	local race = pmeta:get_string("classes:race")
ack

2022-12-28 20:12 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +--	races.update_player(name, race_and_gender, races.default_skin)
забыл удалить закомментированный код

2024-05-21 11:29 UTC, alek13 commented
@vladtcvs , сможешь посмотреть что тут было ?

2024-05-21 11:36 UTC, alek13 commented
@vladtcvs , возможно многое поменялось, надо бы вспомнить что тут.
Создал ветку в Дискорд: https://discord.com/channels/268093825975713793/1242440032711606323

2024-12-23 18:58 UTC, alek13 commented
PR устареыший, требует кучу доработок, но нам нужны скрипты из него.
Поэтому пока оставляю висеть как напоминалка. И перевожу в черновик.

2025-04-15 09:27 UTC, alek13 commented
Окончательный переезд сделан в рамках #2164

2025-04-15 09:27 UTC, closed without merging