Mtg flowers update
lord-server/lord pull request #488
Opened 2021-11-17 16:22 UTC by kevicky9

#278

2021-11-18 10:16 UTC, weqqr requested changes

2021-11-19 04:46 UTC, kevicky9 commented on mods/_minetest_game/flowers/init.lua
> -minetest.register_node("flowers:cactus_decor", {
@weqqr, кто? Кактус? Его больше нет в MTG... Надо в прописывать в overwrites

2021-11-21 14:57 UTC, kevicky9 commented
Помещаем данное обновление на удержание, так как надо ждать обновления `default` из-за какого-то декоративного кактуса

2021-12-18 17:39 UTC, alek13 commented on mods/_minetest_game/flowers/init.lua
> -minetest.register_node("flowers:cactus_decor", {
не, это даже не overwrites, это просто наш отдельный декор-кактус, нужно в наш от дельный мод перекинуть просто

2022-03-16 20:21 UTC, weqqr commented on mods/_minetest_game/flowers/init.lua
> -minetest.register_node("flowers:cactus_decor", {
#566

2022-03-16 20:21 UTC, weqqr approved these changes

2022-03-16 20:23 UTC, merged