new bucket textures
lord-server/lord pull request #489
Opened 2021-11-21 14:12 UTC by VanicGame

![screenshot_20211121_170810](https://user-images.githubusercontent.com/82447582/142765177-d7c9674c-8510-4926-9594-50581f389917.png)

2021-11-21 14:24 UTC, weqqr approved these changes
✔

2021-11-27 22:07 UTC, alek13 commented
договорились немного перерисовать

2021-11-27 22:08 UTC, alek13 requested changes
договорились немного перерисовать

2021-12-18 17:33 UTC, alek13 commented
ждём обновлённых (более конусовидных), что ты присылал в Discord

2022-03-21 10:42 UTC, closed without merging