Update mods: MTG/dye
lord-server/lord pull request #507
Opened 2021-12-13 17:31 UTC by zhelnin-a

Update to commit MTG `5.4.1` (`42baede13fdf855773cc44ce10f4a3ea4e239404`)

- textures mv `_overwrites/MTG/dye/textures`
- register craft of  `dye` from `default:dirt`, `default:grass_1`, `lottplants:lorien_grass_1`
- register craft of `dye` frorm `group:leaves` by colors

Tested in local environment.

Fix #275

2021-12-14 18:33 UTC, weqqr commented on mods/lord/_overwrites/MTG/dye/init.lua
> +-- (!) сделано без циклов, чтобы выдавалось в поиске по проекту
Если сделать так, то копипаста уйдёт, а возможность искать останется
```lua
local recipes = {
    ["dye:white"] = "color_white",
    ["dye:grey"] = "color_grey",
    ...
}
for output, group in pairs(recipes) do
    ...
end
```

2021-12-14 18:34 UTC, weqqr requested changes
Работает ✔

2021-12-15 05:42 UTC, zhelnin-a commented on mods/lord/_overwrites/MTG/dye/init.lua
> +-- (!) сделано без циклов, чтобы выдавалось в поиске по проекту
У меня примерно так и сгенерирована была эта часть кода. Я бы вообще просто цикл оставил из глобальных 'dye.dyes' Специально делал так, для единообразности с тем, что прописывал @alek13 в `_overwrites/MTG/default` и для наглядности. Ну и без цикла, мне кажется нагляднее.

Вот так у меня было изначально было.
```
for _, row in ipairs(dye.dyes) do
	local name = row[1]
	minetest.register_craft({
		output = "dye:" .. name .. " 4",
		recipe = {
			{"group:leaves,color_" .. name}
		},
	})
end
```

2021-12-15 15:52 UTC, weqqr approved these changes

2021-12-18 17:26 UTC, alek13 approved these changes

2021-12-18 17:29 UTC, merged

2021-12-18 17:30 UTC, alek13 commented
т.к. нет новых нод/итемов и пр, а только новый варианты крафтов, решили оставить тут