Update mods: MTG/wool
lord-server/lord pull request #509
Opened 2021-12-20 16:55 UTC by zhelnin-a

Update mod **MTG/wool**

- Update mod `minetest_game/wool` to commit MTG 5.4.1 (`42baede13fdf855773cc44ce10f4a3ea4e239404`)
- Our textures are moved to `lord/_overwrites/MTG/wool/textures` and optimized downsizing
- Custom stairs&slab are moved to a separate mod `lord/lord_wool`

Update mod **MTG/stairs** (due to translation optimization)
- Updated mod `minetest_game/stairs` to commit MTG 5.4.1 (`42baede13fdf855773cc44ce10f4a3ea4e239404`)
- Temporary fixes have been in made `minetest_game/stairs/init.lua`, see `lord/_overwrites/MTG/stairs/readme.md`

Tested in local environment.

Fix lord-server/lord#282

2021-12-20 17:01 UTC, zhelnin-a commented
Обновление `MTG/stairs` вынужденное. В обновлении учтены проблемы с невозможностью  перевода `inner_stairs` и `outer_stairs` без увеличения кода в четыре раза.

Временно заменено для совместимости `default.node_sound_ice_defaults()` на `default.node_sound_glass_defaults()` в `_minetest_game/stairs/init.lua#L870` 
Можно будет восстановить, когда обновится MTG/default/functions.lua

2022-01-03 23:17 UTC, weqqr requested changes
✔

2022-01-03 23:17 UTC, weqqr commented on mods/lord/_overwrites/MTG/stairs/init.lua
> +-- stairs/init.lua
Я правильно понимаю, что этот мод нужен для двух строчек в README?

2022-01-03 23:17 UTC, weqqr commented on mods/_minetest_game/stairs/init.lua
> +	default.node_sound_glass_defaults(), -- Вернуть, когда обновится MTG/default/functions.lua
Лучше было бы сделать отдельно PR для stairs и поверх него ещё один для wool, но и так сойдёт 🤷‍♂️

2022-01-03 23:17 UTC, weqqr commented on mods/lord/lord_wool/init.lua
> +  )
Отступы табами должны быть.

2022-01-03 23:31 UTC, weqqr commented on mods/lord/_overwrites/MTG/stairs/init.lua
> +-- stairs/init.lua
FYI: В #483 тоже делается overwrite для stairs

2022-01-04 05:59 UTC, zhelnin-a commented on mods/lord/lord_wool/init.lua
> +  )
Да, табуляцию перед закрывающей скобкой просмотрел

```suggestion
	)
```

2022-01-04 06:05 UTC, zhelnin-a commented on mods/lord/lord_wool/init.lua
> +end
Добавлено было для понимания "откуда ноги растут". Расписывать эту функцию в виде документации  смысла не вижу. Предлагаю удалить.

```suggestion
```

2022-01-04 06:13 UTC, zhelnin-a commented on mods/_minetest_game/stairs/init.lua
> +	default.node_sound_glass_defaults(), -- Вернуть, когда обновится MTG/default/functions.lua
Да, согласен. В будущем, так и буду делать.

2022-01-04 13:20 UTC, zhelnin-a commented on mods/lord/_overwrites/MTG/stairs/init.lua
> +-- stairs/init.lua
Если коротко, то да.

Если более полно, то в #483 :
- в файле `_overwrites/MTG/readme.md` отсутствует упоминание, что есть переопределения для `MTG/stairs`
- отсутствует файл `reademe.md` в `_overwrites/MTG/stairs/`
- #509 и #483 были с разницей в один день, поэтому такое наложение.

Проблем при мерже быть не должно, если этот PR принять первым. 
Если это не правильно, то хотелось бы понять и делать в будущем так, как правильно.

2022-01-06 16:13 UTC, weqqr approved these changes

2022-01-06 16:15 UTC, merged