Update mods: MTG/screwdriver
lord-server/lord pull request #516
Opened 2022-01-06 18:23 UTC by zhelnin-a

- update mod `minetest_game/screwdriver` to commit MTG 5.4.1 (`42baede13fdf855773cc44ce10f4a3ea4e239404`)
- screwdrivers moved to `lord/lord_screwdriver`

Fix lord-server/lord#280

2022-01-06 19:19 UTC, weqqr requested changes
✔

2022-01-06 19:19 UTC, weqqr commented on mods/lord/lord_screwdriver/init.lua
> +		screwdriver.handler(itemstack, user, pointed_thing, screwdriver.ROTATE_AXIS, 200)
Можно 200 и 2000 вынести как переменные?

2022-01-06 19:19 UTC, weqqr commented on mods/lord/lord_screwdriver/locale/lord_screwdriver.ru.tr
> +Galvorn Screwdriver=Гальворновая отвёртка
Во всех остальных местах galvorn это галворн, не гал**ь**ворн

2022-01-06 19:19 UTC, weqqr commented on mods/lord/lord_screwdriver/init.lua
> +-- Standart Screwdriver based on MTG
standard

2022-01-07 04:35 UTC, zhelnin-a commented on mods/lord/lord_screwdriver/locale/lord_screwdriver.ru.tr
> +Galvorn Screwdriver=Гальворновая отвёртка
```suggestion
Galvorn Screwdriver=Галворновая отвёртка
```

2022-01-07 04:37 UTC, zhelnin-a commented on mods/lord/lord_screwdriver/init.lua
> +-- Standart Screwdriver based on MTG
```suggestion
-- Standard Screwdriver based on MTG
```

2022-01-07 04:43 UTC, zhelnin-a commented on mods/lord/lord_screwdriver/init.lua
> +		screwdriver.handler(itemstack, user, pointed_thing, screwdriver.ROTATE_AXIS, 200)
Специально не стал делать. Отдельным PR будут другие отвертки и уже циклом из массива генерироваться. В этом не стал делать, что бы путаницы не было и легче было review делать.

2022-01-07 04:44 UTC, zhelnin-a commented on mods/lord/readme.md
> + - Отвёртки `lord_screwdriver:screwdriver_galvorn`, `lord_screwdriver:screwdriver_galvorn`
```suggestion
 - Отвёртки `lord_screwdriver:screwdriver`, `lord_screwdriver:screwdriver_galvorn`
```

2022-01-07 08:09 UTC, weqqr commented on mods/lord/_overwrites/MTG/screwdriver/readme.md
> +- Гальворновая отверта `screwdriver:screwdriver_galvorn` теперь `lord_screwdriver:screwdriver_galvorn`
```suggestion
- Галворновая отверта `screwdriver:screwdriver_galvorn` теперь `lord_screwdriver:screwdriver_galvorn`
```

2022-01-07 08:10 UTC, weqqr approved these changes

2022-01-07 08:16 UTC, merged