List arenas in config
lord-server/lord pull request #529
Opened 2022-01-20 03:54 UTC by vladtcvs

2022-09-06 06:53 UTC, weqqr requested changes

2022-09-06 06:53 UTC, weqqr commented on mods/lord/player/arena_health.lua
> +local ids = mysplit(arena_ids, ",")
Вся эта радость должна быть заменена на `string.split()` и `string.trim()`

2022-09-21 23:25 UTC, alek13 commented on mods/lord/player/arena_health.lua
> +local ids = mysplit(arena_ids, ",")
@vladtcvs ping

2022-09-21 23:30 UTC, alek13 commented
висит давно, правки пока не приехали, пока что в draft отправлю

2022-12-07 20:47 UTC, alek13 commented on mods/lord/player/arena_health.lua
> +local ids = mysplit(arena_ids, ",")
исправлено

2022-12-07 20:51 UTC, weqqr approved these changes
жду конфиг

2022-12-07 21:03 UTC, merged