Palantir
lord-server/lord pull request #532
Opened 2022-01-20 03:55 UTC by vladtcvs

2022-02-06 17:06 UTC, zhelnin-a commented on mods/_lott/lottblocks/palantiri.lua
>  		--print(dump(v))
Похоже лишнее

2022-02-06 17:07 UTC, zhelnin-a commented on mods/_lott/lottblocks/palantiri.lua
>  	--print(dump(races_p))
Похоже лишнее

2022-02-06 17:42 UTC, zhelnin-a commented on mods/_lott/lottblocks/palantiri.lua
>  		--print(dump(v))
```suggestion
```

2022-02-06 17:42 UTC, zhelnin-a commented on mods/_lott/lottblocks/palantiri.lua
>  	--print(dump(races_p))
```suggestion
```

2022-02-06 17:51 UTC, zhelnin-a commented
@vladtcvs так понимаю это относится к #440 
Думаю, стоит описание добавит к PR и удалить в коде подобное: `--print(dump(races_p))`

2022-02-06 18:00 UTC, vladtcvs commented on mods/_lott/lottblocks/palantiri.lua
>  	--print(dump(races_p))
Этот `--print()` не я писал, я в данном PR не занимаюсь чисткой или рефакторингом кода, а реализую функционал.

2022-02-06 18:01 UTC, vladtcvs commented on mods/_lott/lottblocks/palantiri.lua
>  		--print(dump(v))
Аналогично, лучше отдельно потом пройтись по коду, привести его в чистый вид, может отрефакторить что. Это тема для отдельного PR

2022-09-16 20:53 UTC, alek13 requested changes
выглядит как черновик. плюс есть конфликты.
пока конвертну в draft

2022-09-16 20:53 UTC, alek13 commented on mods/_lott/lottblocks/palantiri.lua
> +-- Will be used later
тут что-то явно недоделано

2023-01-15 17:46 UTC, closed without merging