Removal modification `MTG/boats` in `lord/lord_boats`
lord-server/lord pull request #534
Opened 2022-02-02 16:12 UTC by zhelnin-a

- Completely removed mod `MTG/boats`
 - Boats code based on 
`MTG/boats`(42baede13fdf855773cc44ce10f4a3ea4e239404)
 - Boats can be used as fuel and catch fire from external influences
 - Added cruise mode (Forward+Back), based on `minetest_game/boats`
 - Fixed player diving underwater when getting up from a boat
 - Now `sail_boat` moves backward at the speed of `row_boat`
 - Changed `collisionbox` for the boats
 - Fixed position of the player in the boats
 - Edited `rowboat_inventory.png` for better display in inventory

 - Size optimization:
    rowboat_inventory.png 444 -> 341
    rowboat_wield.png 366 -> 289
    sailboat_inventory.png 1622 -> 478
    sailboat.png 1251 -> 405
    sailboat_wield.png 889 -> 334
    rowboat.x 23410 -> rowboat.obj 14748
    sailboat.b3d 51460 -> sailboat.obj 33665

Feat: Added cruise mode (Forward+Back)
Fix: lord-server/lord#270

2022-02-02 17:54 UTC, weqqr requested changes
В `sailboat.lua` и `rowboat.lua` *очень* много дублирующегося кода, надо бы его объединить.

2022-02-02 17:54 UTC, weqqr commented on mods/lord/lord_boats/init.lua
> +  local new_entitie = entity_name[2]
`entity`

2022-02-02 17:54 UTC, weqqr commented on mods/lord/lord_boats/init.lua
> +  minetest.register_entity(":" .. old_entitie, {
`entity`

2022-02-03 04:51 UTC, zhelnin-a commented on mods/lord/lord_boats/init.lua
> +  minetest.register_entity(":" .. old_entitie, {
```suggestion
  minetest.register_entity(":" .. old_entity, {
```

2022-02-03 04:52 UTC, zhelnin-a commented on mods/lord/lord_boats/init.lua
> +  local new_entitie = entity_name[2]
```suggestion
  local old_entity = entity_name[1]
  local new_entity = entity_name[2]
```

2022-02-03 04:56 UTC, zhelnin-a commented on mods/lord/lord_boats/init.lua
> +          minetest.log("none", pos_log .. " " .. old_entitie .. " was replaced with " .. new_entitie)
```suggestion
          minetest.add_entity(pos, new_entity)
          minetest.log("none", pos_log .. " " .. old_entity .. " was replaced with " .. new_entity)
```

2022-02-03 05:03 UTC, zhelnin-a commented
> В `sailboat.lua` и `rowboat.lua` _очень_ много дублирующегося кода, надо бы его объединить.

Согласен, нужен рефакторинг, но предлагаю оставить пока так. Тем более, что наверняка в процессе боевого тестирования что-то придётся править.

2022-02-03 09:14 UTC, weqqr commented on mods/lord/lord_boats/rowboat.lua
> +		minetest.chat_send_all(dump(pointed_thing.under))
Вот это лишнее

2022-02-03 09:17 UTC, weqqr commented
Если мерджить в таком виде, то обязательно нужен issue чтобы потом не забыть.

2022-02-04 04:31 UTC, zhelnin-a commented on mods/lord/lord_boats/rowboat.lua
> +		minetest.chat_send_all(dump(pointed_thing.under))
epic fail )
```suggestion
```

2022-02-04 15:09 UTC, merged