Repairing endless shops of `lord_money`
lord-server/lord pull request #536
Opened 2022-02-05 14:00 UTC by zhelnin-a

- added checks the items sold must be wear-free
 - added check for availability of price and offer
 - fixed work of endless shops
 - light refactoring
 - textures optimizations:
    money_copper_coin.png 508 -> 255
    money_diamond_coin.png 1605 -> 543
    money_gold_coin.png 592 -> 267
    money_silver_coin.png 598 -> 276
    shop_chest_top.png 713 -> 270
    shop_license.png 255 -> 154

Fix: lord-server/lord#512

2022-02-11 11:32 UTC, weqqr requested changes
#512 чинит, но логика обмена по-прежнему слишком запутанная, надо тщательно тестировать

2022-02-11 11:32 UTC, weqqr commented on mods/lord/lord_money/init.lua
> +-- lord_money/init.lua
Но зачем?

2022-02-11 11:32 UTC, weqqr commented on mods/lord/lord_money/shop.lua
>  			end
Тут отступы сломались

2022-02-11 16:04 UTC, zhelnin-a commented on mods/lord/lord_money/init.lua
> +-- lord_money/init.lua
Попутно дополнил.  Во всех `MTG`-модулях так делает. Или зря сделал? Поясни, пожалуйста.

2022-02-11 16:18 UTC, zhelnin-a commented on mods/lord/lord_money/shop.lua
>  			end
Вот это поворот.... Исправил.
```suggestion
			for _,list in pairs({"customer_gives", "customer_gets"}) do
				if not pinv:is_empty(list) then
					for i, stack in ipairs(pinv:get_list(list)) do
						if pinv:room_for_item("main", stack) then
							pinv:add_item("main", stack) -- если помещается, кидаем в main,
						else
							minetest.log(
								"action",
								"магазин " .. pos .. " - игрок " .. name ..
								" инвентарь полон, товар " .. stack:get_name() .. " бросили рядом")
							minetest.item_drop(stack, sender, sender:get_pos()) -- если нет - кидаем на пол
						end
						pinv:set_stack(list, i, nil) -- Удаляем элемент i из list
					end
				end
			end
```

2022-02-11 16:36 UTC, zhelnin-a commented
> #512 чинит, но логика обмена по-прежнему слишком запутанная, надо тщательно тестировать

Вдоль и поперёк протестировал, насколько возможно было это сделать локально. Даже копию карты сохранил, где у нас бесконечные прилавки, и там тестировал )
Единственная проблема, которую обнаружил: не сравнивается `wear` стеков оплаты покупателя с `wear` стеков цены продавца. Но там мне по простому не удалось допилить, а прилавки починить надо бы. Вся проблема в том, что функция contains_item(list, stack) не учитывает износ. Но я работаю в этом направлении.
Думаю, что т.к. основная проблема решена, то можно принять PR

2022-02-12 17:08 UTC, weqqr commented on mods/lord/lord_money/init.lua
> +-- lord_money/init.lua
Не ясно, что именно обеспечивает этот комментарий. А если строчка просто потому, что в MTG так же, то это уже cargo cult programming получается :). Не критично.

2022-02-12 17:09 UTC, weqqr approved these changes

2022-02-12 17:11 UTC, merged