Mountain
lord-server/lord pull request #537
Opened 2022-02-11 16:32 UTC by vladtcvs

Fix: #425

2022-05-25 20:42 UTC, alek13 requested changes

2022-05-25 20:42 UTC, alek13 commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Building height map")
лишнее логирование

2022-05-25 20:42 UTC, alek13 commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Processing chunks...")
тоже

2022-05-25 20:42 UTC, alek13 commented on mods/lord/mountgen/mountgen.lua
> +		minetest.log("\t"..id.."/"..table.getn(chunks).." : "..lp1.x..
тоже

2022-05-25 20:42 UTC, alek13 commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Processing chunks done")
тоже

2022-05-25 21:42 UTC, vladtcvs commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Building height map")
fixed

2022-05-25 21:42 UTC, vladtcvs commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Processing chunks...")
fixed

2022-05-25 21:42 UTC, vladtcvs commented on mods/lord/mountgen/mountgen.lua
> +		minetest.log("\t"..id.."/"..table.getn(chunks).." : "..lp1.x..
fixed

2022-05-25 21:42 UTC, vladtcvs commented on mods/lord/mountgen/mountgen.lua
> +	minetest.log("Processing chunks done")
fixed

2022-05-26 17:01 UTC, alek13 approved these changes

2022-05-26 17:03 UTC, merged