Extended Tooltips
lord-server/lord pull request #589
Opened 2022-04-21 21:49 UTC by alek13

2022-07-24 10:26 UTC, weqqr requested changes
Неизвестные категории лучше не показывать
![изображение](https://user-images.githubusercontent.com/4698994/180642756-942d67f3-8993-4f05-9f88-72025e85f795.png)
Описания присутствуют не всегда
![изображение](https://user-images.githubusercontent.com/4698994/180642908-969766fc-6933-421b-94f4-1456d31707d5.png)
![изображение](https://user-images.githubusercontent.com/4698994/180642925-ccf39247-022e-4bb1-a2d4-b74647b2c453.png)

2022-07-24 22:55 UTC, alek13 commented
О, а что это за категория  `bendy`... На каком итеме это?

2022-08-23 17:01 UTC, ssdaniel24 commented
@alek13, группа bendy есть `lord_doors:door_gondor`, `doors:door_steel`, `doors:doors_stell_lock` и какой-то инструмент из `worldedit` может добывать их.

2022-08-23 17:07 UTC, Doloment commented
> @alek13, группа bendy есть `lord_doors:door_gondor`, `doors:door_steel`, `doors:doors_steel_lock` и какой-то инструмент из `worldedit` может добывать их.

Мы на созвоне выяснили, что на `bendy` можно забить, потому что тот инструмент — админская кирка 😄

2022-09-08 15:03 UTC, alek13 commented
Фонари пока вынесем в отдельную задачу (separate issue): https://github.com/lord-server/lord/projects/16#card-85540694
Данный функционал реализован в оригинальном [`minetest_tt_base`](https://repo.or.cz/minetest_tt_base.git).
Попросил автора (@Wuzzy2) перенести мод на GitHub для отправки PR (I ask author of original mod to move it on GitHub for contributing)

2022-09-09 20:14 UTC, weqqr approved these changes
✨

2022-09-09 20:33 UTC, merged