Animation
lord-server/lord pull request #596
Opened 2022-04-30 17:47 UTC by VanicGame

![Uploading screenshot_20220430_193154.png…]()

2022-04-30 18:14 UTC, Doloment requested changes

2022-04-30 18:14 UTC, Doloment commented on mods/lord/player/init.lua
> +player_api = {}
????

2022-04-30 18:14 UTC, Doloment commented on mods/lord/player/init.lua
> +function player_api.set_model(player, model_name)
Убирай лишнее

2022-04-30 18:15 UTC, VanicGame commented on mods/lord/player/init.lua
> +function player_api.set_model(player, model_name)
я пытался, ему вечно чего-то нехватает

2022-04-30 18:16 UTC, Doloment commented on mods/lord/player/init.lua
> +function player_api.set_model(player, model_name)
Ниче не знаю, так я это не пропущу

2022-04-30 18:17 UTC, Doloment commented
Пациент отказался переделывать

2022-04-30 18:18 UTC, VanicGame commented
пациент не знает, что надо добавить, чтобы он не вылетал с player_model is NILL value

2022-05-01 09:52 UTC, VanicGame commented
@Doloment

2022-05-01 09:56 UTC, Doloment commented on mods/lord/player/init.lua
> +				player_set_animation(player, is_sneak.."stand", animation_speed_mod)
Конечно у тебя не будет работать анимация, ты же никуда не добавил её включение

2022-05-01 09:57 UTC, Doloment commented on mods/lord/player/init.lua
> +					player_set_animation(player, is_sneak.."walk", animation_speed_mod)
То же самое тут

2022-05-01 09:58 UTC, VanicGame commented on mods/lord/player/init.lua
> +					player_set_animation(player, is_sneak.."walk", animation_speed_mod)
`player_set_animation(player, is_sneak.."walk", animation_speed_mod)`

2022-05-01 09:59 UTC, Doloment commented on mods/lord/player/init.lua
> +					player_set_animation(player, is_sneak.."walk", animation_speed_mod)
Тебе надо "walk" поменять на "sneak_walk", у тебя же в multiskin они так называются

```lua
sneak_stand = {x = 225,  y = 240},
sneak_walk = {x = 251,  y = 272},```

2022-05-01 10:00 UTC, VanicGame commented on mods/lord/player/init.lua
> +					player_set_animation(player, is_sneak.."walk", animation_speed_mod)
Так тебе `is_sneak` ни о чем не говорит?

2022-05-01 10:02 UTC, VanicGame commented on mods/lord/player/init.lua
> +				player_set_animation(player, is_sneak.."stand", animation_speed_mod)
Эта анимация работает

2022-05-01 10:05 UTC, Doloment commented
Решили что ненадо нам этого, а надо #403 делать

2022-05-01 10:05 UTC, closed without merging