Removing depends.txt + Fix warnings about mod.conf lack
lord-server/lord pull request #614
Opened 2022-06-08 09:01 UTC by ssdaniel24

2022-06-10 16:39 UTC, Doloment requested changes

2022-06-10 16:39 UTC, Doloment commented on mods/lord/alarm/mod.conf
> +name = alarm
Файл зависимостей удалён, но зависимости не указаны

2022-06-12 14:03 UTC, ssdaniel24 commented on mods/lord/alarm/mod.conf
> +name = alarm
Файл был пуст

2022-06-12 15:46 UTC, Doloment approved these changes
Допустим, "мяу"

2022-08-16 18:33 UTC, weqqr approved these changes
✨

2022-08-16 18:36 UTC, merged