Lord bees
lord-server/lord pull request #623
Opened 2022-06-30 07:38 UTC by VanicGame

Добавлены новые блоки:
![screenshot_20220630_102621](https://user-images.githubusercontent.com/82447582/176619124-e9ff0ee1-8853-440f-8f20-4135af975bdf.png)

Обновлены текстуры ульев + добавлены заполненные ульи и механика их появления:
![screenshot_20220630_102814](https://user-images.githubusercontent.com/82447582/176618327-cbd821dc-17e8-4d0a-a82e-4b740e7f7647.png)

Обновлены текстуры центрифуги:
![screenshot_20220630_103144](https://user-images.githubusercontent.com/82447582/176619081-435983b8-f3d0-44b5-8844-8a09a6c85f0e.png)

Добавлены фоны в формспеки ульев и центрифуги:
![изображение](https://user-images.githubusercontent.com/82447582/176619461-730dce32-33e8-425a-b8cd-502147ee81f0.png)

Раскомментирован и исправлен код для имитации вылета пчёл из ульев (вылетают только при наличии матки):
![изображение](https://user-images.githubusercontent.com/82447582/176619794-155c3ff2-5c41-447e-a079-ae0dfe0eecc4.png)

Для новых блоков имеются крафты

Заменен локализатор

Удалены ненужные текстуры

Частично почищен код

Регистрация ульев разнесы в разные папки

Поправлено размножение цветов

Добавлено описание в README

2022-06-30 19:53 UTC, Doloment commented
@VanicGame глянь https://github.com/VanicGame/lord-1/pull/1 :D

2022-06-30 20:04 UTC, Doloment commented
?!?!?!
![image](https://user-images.githubusercontent.com/22934348/176767957-0be148bf-967a-4365-a61d-62cbc8ddc584.png)

2022-06-30 20:07 UTC, VanicGame commented
> ?!?!?! ![image](https://user-images.githubusercontent.com/22934348/176767957-0be148bf-967a-4365-a61d-62cbc8ddc584.png)

Это ты сам поставил? Он лепится к блоку, на который установлен...

2022-06-30 20:32 UTC, Doloment requested changes

2022-06-30 20:32 UTC, Doloment commented on mods/lord/bees/init.lua
> +          --tool:add_wear(2)
А чё бы не добавлять износ?

2022-06-30 20:32 UTC, Doloment commented on mods/lord/bees/init.lua
> +  })
Нету звуков — не прикольно

2022-06-30 20:32 UTC, Doloment commented on mods/lord/bees/init.lua
> +  })
Нету звуков — не прикольно

2022-06-30 20:33 UTC, Doloment commented on mods/lord/bees/init.lua
> +     label = " formspec extractor replacement",
Отступы отдельно поправлю, а вот фигню в кавычках убери

2022-07-01 07:07 UTC, VanicGame commented on mods/lord/bees/init.lua
> +          --tool:add_wear(2)
А это не я закомментировал, давай добавлю

2022-07-01 07:07 UTC, VanicGame commented on mods/lord/bees/init.lua
> +  })
Звуки есть, дефолтные

2022-07-01 07:08 UTC, VanicGame commented on mods/lord/bees/init.lua
> +  })
Звуки есть, дефолтные

2022-07-01 07:15 UTC, Doloment commented on mods/lord/bees/init.lua
> +  })
Ты выдишь строчку sound в определении? И я не вижу. Зайди в игру, попрыкай по блоку. Звуков нет

2022-07-01 07:15 UTC, Doloment commented on mods/lord/bees/init.lua
> +  })
Ты выдишь строчку sound в определении? И я не вижу. Зайди в игру, попрыгай по блоку. Звуков нет

2022-07-01 07:15 UTC, VanicGame commented on mods/lord/bees/init.lua
> +  })
У меня есть

2022-08-19 17:47 UTC, Doloment approved these changes

2022-08-19 17:51 UTC, merged