Lottplants last update
lord-server/lord pull request #646
Opened 2022-07-15 12:10 UTC by ssdaniel24

# lottplants update

Обновления стянуты с [последнего коммита](https://github.com/minetest-LOTR/Lord-of-the-Test/tree/8b89ca252cb668a269e3656ac756ca26d24870a0).

**flowers.lua**:
- все растения теперь извиваются при включенных шейдерах: `waving = 1`;
- большинство растений теперь `paramtype2 = "meshoptions"` и выглядят по-разному;
- теперь почти из всех растений выпадают сами растения в некотором кол-ве;

**functions.lua**:
- почищены комментарии с кодом и пустые строки в ненужных местах;
- обнаружено очень много дублирующегося кода, в будущем предлагаю переработать;

**init.lua**:
- растения теперь извиваются - `waving = 1`;
- изменён внешний вид растений с помощью `paramtype2 = "meshoptions"`;

**nodes.lua**:
- листья и саженцы теперь извиваются при включенных шейдерах;

**wild_food.lua**:
- добавлены `waving = 1` и `paramtype2 = "meshoptions"`
- изменёна "добыча" (drop) с грибов (`mushroom_wild`)

P.S.: `default:leaves` и `default:jungleleaves` извиваются неправильно, нужно править!

2022-07-20 16:40 UTC, weqqr requested changes
`paramtype2 = "meshoptions"` это круто, но:
- Мапген не в курсе про place_param2, его надо научить.
- Старые цветы надо исправлять через LBM.

2022-07-20 16:40 UTC, weqqr commented on mods/_lott/lottplants/wild_food.lua
> +			{ items = {'lottfarming:white_mushroom_spore'}, rarity = 20}
unknown item

2022-07-20 16:40 UTC, weqqr commented on mods/_lott/lottplants/flowers.lua
> +		max_items = 3,
`max_items = 3`, но списка два

2022-07-20 16:40 UTC, weqqr commented on mods/_lott/lottplants/flowers.lua
> +		max_items = 2,
`max_items = 2`, но список один

2022-07-20 16:40 UTC, weqqr commented on mods/_lott/lottplants/flowers.lua
> +	place_param2 = 40,
Смещение выглядит очень странно (касается и остальных цветов с маской `param2 = ... | 8`)

2022-07-20 16:43 UTC, ssdaniel24 commented on mods/_lott/lottplants/flowers.lua
> +	place_param2 = 40,
Как же тогда сделать? Оставить как было?

2022-07-20 16:44 UTC, weqqr commented on mods/_lott/lottplants/flowers.lua
> +	place_param2 = 40,
Думаю лучше убрать `8`, но оставить `32`

2022-07-21 14:26 UTC, weqqr approved these changes
✨

2022-07-21 18:08 UTC, merged