Add core_callbacks
lord-server/lord pull request #699
Opened 2022-08-14 19:22 UTC by VanicGame

**Описание PR:**
Добавлены `core_callbacks` из локального и индивидуального проекта `lord2`. В связи с немного иной структурой проекта я вынес `core_function` (основной файл с глобальными функциями для `lord2`, аналог `lordlib`, наверное) в отдельный файл для удобства.

Для чего добавил: Во-первых, это полезная фигня, во-вторых, следующими PR пойдут стягивания с `lord2` механики лука, для обкатывания на сервере (подробности спросите у меня), а так же стягивания механики еды (это далеко в перспективе). Я бы мог добавить её вместе с механикой лука, но решил разделить.

Что умеет: библиотека содержит обратные вызовы для таких случаев, когда игрок нажал клавишу из списка controls, удерживает её, отпускает и меняет предмет в руке.

**Рекомендации к тесту:**

Пока что ничего

**Дополнительная информация:**

---

2022-08-16 11:13 UTC, weqqr requested changes
А можно документацию к API? Хотя бы описания принимаемых аргументов

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	core_callback.players[player:get_player_name()] = {
Аналогично, где проверка `player:get_player_name() ~= nil`?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	core_callback.players[player:get_player_name()] = nil
`player:get_player_name() ~= nil`?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +					func(player, control_name, minetest.get_us_time()/1000000-player_last_controls[control_name][2], dtime)
`1000000` повсюду используется, оформи как константу

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +		local player_name = player:get_player_name()
`player_name ~= nil`?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +minetest.register_globalstep(function(dtime)
Большая и сложная функция, можно её на части поменьше разбить?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +core_callback = {}
У нас уже есть таблица `lord`, может лучше в неё?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +					func(player, control_name, minetest.get_us_time()/1000000-player_last_controls[control_name][2])
`minetest.get_us_time()/1000000-player_last_controls[control_name][2]` повторяется и тяжело читается, можно все эти вычисления вынести в одно место, чтобы чётко и по шагам было написано, что это такое?

2022-08-16 11:13 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +			place = {false},
Если я правильно понял, эти таблицы будут дополняться параметрами во время выполнения, можно сразу сюда значения по умолчанию внести?

2022-08-16 11:55 UTC, VanicGame commented on mods/lord/lordlib/core_functions.lua
> +core_callback = {}
Хотелось бы оставить так, как писал. Потому что в lord_bows пишется именно core_callbacks

2022-08-16 18:31 UTC, weqqr requested changes

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	if not control_name then return end
```suggestion
	if not control_name then
		return
	end
```

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	if not player_name then return end
```suggestion
	if not player_name then
		return
	end
```

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	if not player_name then return end
```suggestion
	if not player_name then
		return
	end
```

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +	if not player_name then return end
```suggestion
	if not player_name then
		return
	end
```

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +--- register_on_press(player, control_name)
Не совпадает с сигнатурой функции

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +--- register_on_release(player, control_name, release_time)
Не совпадает с сигнатурой функции

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +--- register_on_hold(player, control_name, hold_time, dtime)
Не совпадает с сигнатурой функции

2022-08-16 18:31 UTC, weqqr commented on mods/lord/lordlib/core_functions.lua
> +--- register_on_wield_index_change(player, player_wield_index, player_last_wield_index)
Не совпадает с сигнатурой функции

2022-08-20 16:30 UTC, alek13 commented on mods/lord/lordlib/core_functions.lua
> +end
```suggestion
---
--- Регистрирует обратный вызов на нажатие кнопки из списка controls.
---
--- @param func fun(player:Player, control_name:string)
--- Принимает функцию колбека со след параметрами:
---  * `player` - игрок
---  * `control_name` - кнопка из списка controls
lord.register_on_press = function(func)
	table.insert(lord.registered_on_press, func)
end
```

2022-08-20 16:39 UTC, alek13 requested changes

2022-08-20 16:39 UTC, alek13 commented on mods/lord/lordlib/core_functions.lua
> +function call_press(player, player_last_controls, control_name)
`local`

2022-08-20 16:39 UTC, alek13 commented on mods/lord/lordlib/core_functions.lua
> +function call_hold(player, player_last_controls, control_name, dtime)
`local`

2022-08-20 16:39 UTC, alek13 commented on mods/lord/lordlib/core_functions.lua
> +function call_release(player, player_last_controls, control_name)
`local`

2022-09-02 19:45 UTC, alek13 commented on mods/lord/lordlib/core_functions.lua
> +		if player_name ~= nil then
лучше делать наоборот:
```
  if ( ! player_name) {
    continue;
  }

  // дальше остальной код
```

ф-ция и правда большая

2022-09-03 02:06 UTC, weqqr approved these changes

2022-09-03 04:20 UTC, merged