Lord bows
lord-server/lord pull request #700
Opened 2022-08-15 11:19 UTC by VanicGame

**Описание PR:**

Добавлены луки с механикой натягивания тетивы и стрелы с поворотом в сторону вектора движения.

Алек предложил добавить пока без крафтов, чтобы просто посмотреть, как это будет выглядеть на сервере.

Возможно, в будущем, этот мод сольётся с throwing.

**Рекомендации к тесту:**

Достать лук и стрелы из list и пострелять из него стоя, в движении, под зельками, на лошади (не пробовал, кстати), по игрокам в броне, без, по разным мобам, в том числе менялам и лошадям.

**Дополнительная информация:**

Мержить после #699

2022-08-20 09:42 UTC, VanicGame commented
#76

2022-09-01 19:36 UTC, Doloment commented
При определённых обстоятельствах лук не реагирует на отпускание кнопки мыши.
Также стоит убрать фазу лука из креативного инвентаря, добавив им группу `not_in_creative_inventory`

2022-09-18 17:16 UTC, alek13 requested changes
ещё для всех функций, включая local, хотелось бы видеть doc-блоки

2022-09-18 17:16 UTC, alek13 commented on mods/lord/lord_bows/entities_projectiles.lua
> +			-- Обновление таймера жизни
коммент бессмысленный: название ф-ции говорит ровно тоже самое.
в комменте должно описываться "для чего это делается", а не "что делает код", либо не оставлять вообще.
https://www.google.com/search?channel=fs&client=ubuntu&q=right+code+comments

2022-09-18 17:16 UTC, alek13 commented on mods/lord/lord_bows/entities_projectiles.lua
> +local function collision_handling(self, moveresult, name, def)
превый параметр это не совсем `self`.
Видя `self`, ожидаешь, что это метод объекта, в который и передаётся `this`, а оказывается это не так. Для справки: [дока](https://www.lua.org/pil/16.html), [короткое объяснение с примером](https://stackoverflow.com/questions/71580346/what-is-self-and-what-does-it-do-in-lua)

Тут лучше назвать `entity` наверное -- станет очевидно, если добавить doc-блок пред функцией и указать типы.

2022-09-18 17:16 UTC, alek13 commented on mods/lord/lord_bows/mechanics_throwing.lua
> +-- Если лук заряжался, а итем в руке сменился, то надо разрядить лук (без выстрела)
отличный пример коммента

2022-09-18 17:16 UTC, alek13 commented on mods/lord/lord_bows/init.lua
> +		for k, v in pairs(t2) do
отступ не тот

2023-01-11 17:18 UTC, alek13 commented on mods/lord/lord_bows/init.lua
> +GRAVITY = 9.81
оказывается есть вот такая настройка:
```suggestion
GRAVITY = minetest.settings:get("movement_gravity")) or 9.81
```

2023-01-11 17:20 UTC, alek13 commented on mods/lord/lord_bows/init.lua
> +local function table_concat(t1,t2)
даже не заметил в прошлый раз, но это не конкатенация.
это скорее `table_merge` или `table_overwrite`

2023-01-11 17:21 UTC, alek13 commented on mods/lord/lord_bows/init.lua
> +		},
```suggestion
				times={[1]=3.00, [2]=1.60, [3]=0.60},
				uses=10,
				maxlevel=1
			},
```

2023-01-11 20:39 UTC, merged