MTG/doors update
lord-server/lord pull request #708
Opened 2022-08-20 19:31 UTC by ssdaniel24

Решение #487.

Примечания:
- у `castle:oak_door_lock` убрана своя текстура с ручкой, так как ни одна другая запертая дверь не имеет своей текстуры.

## Протестировать:

Проверить правильность наложения текстуры, описания, подписи, работу в приватах и т.д. у следующих вещей:
- `castle:oak_door`
- `castle:jail_door`
- `castle:oak_door_lock`
- `castle:jail_door_lock`
- `lottblocks:door_alder`
- `lottblocks:door_birch`
- `lottblocks:door_junglewood`
- `lottblocks:door_lebethron`
- `lottblocks:door_mallorn`
- `lottblocks:door_pine`
- `lottblocks:door_alder_lock`
- `lottblocks:door_birch_lock`
- `lottblocks:door_junglewood_lock`
- `lottblocks:door_lebethron_lock`
- `lottblocks:door_mallorn_lock`
- `lottblocks:door_pine_lock`
- `protector_lott:door_wood`
- `protector_lott:door_steel`
- `protector_lott:door_glass`
- `protector_lott:door_obsidian_glass`
- `protector_lott:door_junglewood`
- `protector_lott:door_alder`
- `protector_lott:door_birch`
- `protector_lott:door_pine`
- `protector_lott:door_lebethron`
- `protector_lott:door_mallorn`
- `protector_lott:oak_door`
- `protector_lott:jail_door`
- `lottblocks:hatch_alder`
- `lottblocks:hatch_birch`
- `lottblocks:hatch_junglewood`
- `lottblocks:hatch_lebethron`
- `lottblocks:hatch_mallorn`
- `lottblocks:hatch_pine`

А также проверить замещение старых дверей на новые (см. функцию `doors.register_door`, там lbm-ка).

2022-08-20 19:33 UTC, ssdaniel24 commented
Спасибо офигенной программе `imagemagick`! Чтобы я без неё делал, склеивая эти дурацкие текстурки в UV...
```shell
#!/bin/sh
# Script-helper for converting old door textures to new.

set -e

if [ "$#" -lt 4 ]; then
  cat <<EOF
Usage:
  script.sh <tile_top> <tile_bottom> <edge> <output texture name>
EOF
  exit 1
fi
a_top=$1
b_bottom=$2
edge=$3
output_name=$4

# mirror
a_top_mirrored=${a_top%.*}-mirrored.png
convert -flop "$a_top" "$a_top_mirrored"
b_bottom_mirrored=${b_bottom%.*}-mirrored.png
convert -flop "$b_bottom" "$b_bottom_mirrored"

# two sides for door
output_name_without_edges=${output_name%.*}_without_edges.png
montage "$a_top" "$a_top_mirrored" "$b_bottom" "$b_bottom_mirrored" \
  -geometry +0+0+0+0 \
  -tile 2x2 \
  -background transparent \
  "$output_name_without_edges"

# sides
height=$(identify -ping -format '%H' "$output_name_without_edges")
width=6; [ "$height" = 64 ] && width=12
output_name_edge=${output_name%.*}_edge.png
magick "$edge" \
  -virtual-pixel tile \
  -set option:distort:viewport "$width"x"$height" \
  -distort SRT 0 \
  "$output_name_edge"

# finally
montage "$output_name_without_edges" "$output_name_edge" \
  -tile 2x -geometry +0+0 -background transparent "$output_name"

# tmp deleting
rm -f \
  "$a_top_mirrored" \
  "$b_bottom_mirrored" \
  "$output_name_without_edges" \
  "$output_name_edge"
```

2022-08-20 20:29 UTC, alek13 commented
> Спасибо офигенной программе `imagemagick`! Чтобы я без неё делал, склеивая эти дурацкие текстурки в UV...
> 
> ```shell
> #!/bin/sh
> # Script-helper for converting old door textures to new.
> 
> ....
> ```

закинь этот скриптик в `util`, плиз

2022-08-21 05:53 UTC, ssdaniel24 commented
@alek13, зачем? Он один раз только пригодился и всё. С остальными дверями всё в порядке.

2022-08-21 13:23 UTC, alek13 commented
@ssdaniel24 , да, я понимаю, что он одноразовый. Просто он может пригодиться потом:
 - в качестве "подсмотреть" при решении какой-то другой задачи
 - посмотреть что именно мы сделали при просмотре истории

т.е. лишним не будет

2022-08-21 15:44 UTC, ssdaniel24 commented
@alek13, ну я уже по сути оставил код скрипта в этом PR. Кому надо заглянет сюда.

2022-08-22 14:43 UTC, alek13 commented
никто потом не вспомнит про PR и про то, что там был какой-то скрипт в комментах, да и найти его сложно будет, когда его уже закроют

2022-08-30 07:20 UTC, ssdaniel24 commented
Кстати, добавились калитки для заборов.

2022-09-16 16:49 UTC, alek13 requested changes
что-то пошло не так...
видать залетели коммиты из другого PR.
\+ резолв конфликтов не произошёл, хотя @ssdaniel24 его делал.
пока откладываю review

2022-09-20 11:48 UTC, alek13 commented on .luacheckrc
> +    "mods/lord/_overwrites/MTG/doors/init.lua", -- changing readonly fields to unregister doors
выше в этом файле в `read_globals` есть
```lua
read_globals      = {
	-- ...

	-- Mods APIs
	"doors",

	-- ...
```

этот `doors` можно перенсти в секцию `globals`:
```lua
globals           = {
	"minetest", "core",

	-- Mods APIs
	"doors",
}
тогда блокировать весь файл не нужно

2022-09-20 11:54 UTC, alek13 approved these changes

2022-09-20 12:01 UTC, weqqr approved these changes

2022-09-20 12:59 UTC, alek13 commented on .luacheckrc
> +    -- MTG APIs
пробелы вместо таба.
![image](https://user-images.githubusercontent.com/1972329/191264062-b4a0e3a1-e093-4b7d-98b4-93277254a692.png)

2022-09-21 16:44 UTC, merged