Implemented lord_replacer
lord-server/lord pull request #713
Opened 2022-08-22 15:34 UTC by ssdaniel24

Предлагается альтернатива #705. Данный инструмент будет доступен только для строителей.

**Рекомендации к тесту:**

Посмотреть работоспособность (см как работает:  https://forum.minetest.net/viewtopic.php?t=4676).
Расход материалов должен обязательно происходить.

2022-08-22 16:57 UTC, Doloment requested changes

2022-08-22 16:57 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +	"lottores:tilkal",
```
-- Блоки, которые нельзя заменять
replacer.blacklist["lottores:tilkal"] = true
replacer.blacklist["stairs:slab_tilkal"] = true
replacer.blacklist["stairs:stair_tilkal"] = true
replacer.blacklist["stairs:stair_inner_tilkal"] = true
replacer.blacklist["stairs:stair_outer_tilkal"] = true
replacer.blacklist["lottblocks:palantir"] = true
```
Вот список, стащил у Вани,

2022-08-22 16:57 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +					S("Error: you have selected unloaded node, please wait a moment."))
Ограничения между использованиями же нет, верно? Почему `wait a moment`? Может запутать игрока

2022-08-22 16:58 UTC, Doloment commented
Добавить бы еще проверку на то, есть ли инвентарь у ноды, а то поудаляются вещи, если неправильно использовать с теми же сундуками, например

2022-08-22 19:56 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +	end
```suggestion
	local pointed_meta = minetest.get_meta(pointed_pos)
	local pointed_meta_table = pointed_meta:to_table()
	if pointed_meta and pointed_meta_table.inventory then
		for _, v in pairs(pointed_meta_table.inventory) do
			if v ~= {} then
				minetest.chat_send_player(player_name, S("Error: non-empty node inventory found. Unload it first."))
				return false
			end
		end
	end
```

2022-08-22 19:57 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +	end
Проверка на наличие любого инвентаря, независимо от того, назван ли он `main` или иначе

2022-08-22 20:34 UTC, Doloment approved these changes

2022-08-22 20:55 UTC, alek13 requested changes

2022-08-22 20:55 UTC, alek13 commented on mods/lord/lord_replacer/init.lua
> +local function replacer_get_node(itemstack, pointed_thing, player_name)
док-блок

2022-08-22 20:55 UTC, alek13 commented on mods/lord/lord_replacer/init.lua
> +local function get_replacer_selection(itemstack)
док-блок

2022-08-22 20:55 UTC, alek13 commented on mods/lord/lord_replacer/init.lua
> +local function replacer_set_node(itemstack, pointed_thing, player_name, place_above)
док-блок

2022-08-22 20:55 UTC, alek13 commented on mods/lord/lord_replacer/init.lua
> +	description = S("Node Replacer"),
стоит добавить минимальное описание для пользователя как инструмент работает

2022-08-22 21:18 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +	minetest.set_node(pointed_pos, selected_node)
```suggestion
	local player = minetest.get_player_by_name(player_name)
	if not player then
		return false
	end
	
	local inv = player:get_inventory()
	if not inv:contains_item("main", selected_node.name)
		minetest.chat_send_player(player_name, S("Error: not enough materials."))
		return false
	end
	
	inv:remove_item("main",  selected_node.name)
	minetest.set_node(pointed_pos, selected_node)
```

2022-08-22 21:19 UTC, Doloment commented on mods/lord/lord_replacer/init.lua
> +	minetest.set_node(pointed_pos, selected_node)
Это потребление материала. Там еще в файл локализации надо строчку вписать, но это сам

2022-08-23 07:29 UTC, Doloment approved these changes

2022-08-23 08:23 UTC, Doloment approved these changes

2022-08-23 08:49 UTC, Doloment approved these changes

2022-08-23 20:15 UTC, weqqr approved these changes

2022-08-23 20:20 UTC, merged