Добавление полублоков из стволов деревьев
lord-server/lord pull request #739
Opened 2022-08-26 09:42 UTC by ssdaniel24

Решение #698.

2022-08-30 14:17 UTC, Doloment requested changes

2022-08-30 14:17 UTC, Doloment commented on mods/_lott/lottplants/nodes.lua
> +	{ tree = 1, choppy = 3, flammable = 2 },
Здесь и в остальных регистрациях: убери группу `tree`, ибо она используется в паре крафтов, где важны именно брёвна
Если нужно оставить чтобы они были использованы как топливо, дай им группу типа `tree_slab` и впиши где-то:
```
minetest.register_craft({
	type = "fuel",
	recipe = "group:tree_slab",
	burntime = 7,
})
```

2022-08-30 14:17 UTC, Doloment commented on mods/_lott/lottplants/nodes.lua
> +	"mallorntrunk",
Два раза маллорновое??

2022-08-30 14:53 UTC, Doloment requested changes

2022-08-30 14:53 UTC, Doloment commented on mods/_lott/lottplants/nodes.lua
> +minetest.register_craft({
Ну вон же ниже `--Crafting` стоит, впиши это туда

2022-08-30 17:22 UTC, ssdaniel24 commented on mods/_lott/lottplants/nodes.lua
> +minetest.register_craft({
Это другой крафтинг, не топливный же.

2022-08-30 17:24 UTC, Doloment commented on mods/_lott/lottplants/nodes.lua
> +minetest.register_craft({
Крафтинг есть крафтинг, но собсна ладно. @weqqr чо думаешь, дать поблажку?

2022-08-31 09:26 UTC, weqqr commented on mods/_lott/lottplants/nodes.lua
> +minetest.register_craft({
Думаю крафтинг есть крафтинг

2022-08-31 09:33 UTC, Doloment approved these changes

2022-08-31 09:36 UTC, merged

2022-10-29 23:00 UTC, alek13 commented
Плиты из стволов эвкалипта не крафтятся:
![image](https://user-images.githubusercontent.com/1972329/198855534-78b84d8a-b717-4bff-8e38-f699da0aa4bf.png)

2022-10-29 23:10 UTC, alek13 commented
отбой, не те стволы взял, всё норм