Lottblocks update
lord-server/lord pull request #771
Opened 2022-09-13 08:23 UTC by ssdaniel24

Closes #342. Добавлено:
- дварфийский расовый сундук: открывается только гномами, крафтится сундука, окруженного камнем.
- мифриловая каменная лампа
- гонг

И исправления по мелочи.

*Проверять PR удобно по коммитам.*

2022-09-14 12:34 UTC, alek13 requested changes

2022-09-14 12:34 UTC, alek13 commented on mods/_lott/lottblocks/misc.lua
> +local creative = minetest.settings:get_bool("creative_mode")
тут нужно использовать
```lua
minetest.is_creative_enabled(player_name)
```
на данный момент, он определена в `mods/lord/lordlib/init.lua:49`
при переходе на `5.4+` будет доступна из builtin api

2022-09-14 12:34 UTC, alek13 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
а что за "Гробница гнома" ?
может давай её раскомментим ?
правда я крафта не вижу...
она в оригинале есть ?

2022-09-14 12:38 UTC, ssdaniel24 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
Это структура, которая генерируется под землёй.

2022-09-14 13:10 UTC, ssdaniel24 commented on mods/_lott/lottblocks/misc.lua
> +local creative = minetest.settings:get_bool("creative_mode")
Там идёт проверка креатива глобального, а не отдельного игрока.

2022-09-14 14:02 UTC, alek13 commented on mods/_lott/lottblocks/misc.lua
> +local creative = minetest.settings:get_bool("creative_mode")
ну да, но ты можешь её также без аргумента использовать.
но по хорошему бы заменить эту переменную на inline-использование:
 - передавать `placer` в `place_rope()`
 - внутри `place_rope()` использовать `minetest.is_creative_enabled(placer:get_player_name())`
 т.к. от общего `creative` для всех игроков из настроек нужно уйти.
 
либо тогда вообще не трогать эту строку и оставить
```lua
local creative = default.creative
```

2022-09-14 14:04 UTC, alek13 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
ну ок, так может мы её оставим (раскомментим).
не смотрел что это ?
если там нужно что-то ещё дополнительное для неё, можно в отдельный issue закинуть

2022-09-14 14:38 UTC, ssdaniel24 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
Не зря же это закомментировали давным-давно. Это просто просто небольшая секретка как нянкэт.

2022-09-14 14:39 UTC, alek13 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
комметировали скорее всего потому, что что-то не взлетало.
про секретку не понял... можно созвониться

2022-09-14 14:43 UTC, ssdaniel24 commented on mods/_lott/lottblocks/decoration.lua
> -minetest.register_node("lottblocks:dwarf_tomb_top", {
Добавить можно, но в отдельном PR.

2022-09-15 00:19 UTC, alek13 approved these changes

2022-09-15 00:22 UTC, merged