Add basic definitions for built-in functions and tables
lord-server/lord pull request #778
Opened 2022-09-18 19:50 UTC by weqqr

**Описание PR:**

This commit adds basic, intentionally loosely-typed definitions for built-in Minetest functions and tables.

The plan is to facilitate static type checks across the codebase and slowly populate declarations as required. Going forward, declarations should become stricter as the code moves towards being well-typed.

Naming convention for the included file was chosen to mimic TypeScript's declaration files, as their purpose is quite similar.

No actual errors in the codebase were fixed, this will be done in a follow-up PR.

**Рекомендации к тесту:**

not applicable

2022-09-19 05:41 UTC, ssdaniel24 approved these changes

2022-09-20 12:46 UTC, alek13 requested changes

2022-09-20 12:46 UTC, alek13 commented on util/minetest_types.lua
> +invisibility = nil
лучше наверное
```lua
<mod> = {}
```

2022-09-20 12:46 UTC, alek13 commented on util/minetest_types.lua
> +-- wtf
вроде разобрались, подправь коммент и напиши, что грохнуть после 5.5

2022-09-20 12:49 UTC, alek13 commented on util/minetest_types.lua
> +--- Implementation-specific Lua libraries
это сам MineTest предоставляет какую-то класс-обёрку к JIT что ли ?
weqqr — Today at 3:47 PM
https://luajit.org/ext_jit.html
Alek — Today at 3:48 PM
о, добавь в коммент эту ссыль

2022-09-20 12:52 UTC, weqqr commented on util/minetest_types.lua
> +invisibility = nil
Так не работает, ибо в условии `{}` эквивалентно `true`

2022-09-20 12:54 UTC, alek13 commented on util/minetest_types.lua
> +invisibility = nil
так у нас же методы вызы... тьфу, понял, согласен

2022-09-20 13:00 UTC, alek13 approved these changes

2022-09-20 13:01 UTC, merged