Implemented races.race_stuff_opener
lord-server/lord pull request #787
Opened 2022-09-22 07:30 UTC by ssdaniel24

Resolves #785.

2022-09-23 19:56 UTC, alek13 requested changes

2022-09-23 19:56 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +---@return string @или локализованное название расы, или nil, если взлом не удался или удалось открыть.
```suggestion
--- Проверяет может ли игрок открыть расовый сундуков, дверь и др.
--- Игрок может открыть сундук, если он принадлежит расе `owner_race` или провёл удачный взлом с помощью отмычки.
---
--- @param owner_race string    ID расы, которой принадлежит сундук.
--- @param player     string    никнейм игрока.
--- @param itemstack  ItemStack итем в руке игрока
---
--- @return boolean|nil, string|nil ( 1 - открылся ли сундук или nil, если ошибка; 2 - локализованное название расы сундука/двери/.., если открывать нельзя и нет попытки взлома  или nil, если взлом не удался или удалось открыть )
```

2022-09-23 19:56 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +		return
```suggestion
		return nil
```

2022-09-23 19:57 UTC, alek13 requested changes

2022-09-23 19:57 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +			itemstack:add_wear(65535 / 20)
дубляж строки, лучше вынести перед if'ом

2022-09-23 19:58 UTC, Doloment commented on mods/lord/lord_classes/init.lua
> +		return
Как по мне, допустимое написание

2022-09-23 20:00 UTC, alek13 requested changes

2022-09-23 20:00 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +	local item = itemstack:get_name()
```suggestion

```

2022-09-23 20:00 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +	elseif item == "lottblocks:lockpick" then
```suggestion
	end
	local item = itemstack:get_name()
	if item == "lottblocks:lockpick" then
```

2022-09-23 20:10 UTC, alek13 commented on mods/lord/lord_classes/init.lua
> +		return
> Как по мне, допустимое написание
Допустимое, но лучше всегда возвращать что-то конкретное, тем более в Lua это разные вещи и тем более в этой ф-ции вообще два значения возвращаются тут даже скорее `return nil, nil` нужен.
Ошибку потом устанешь искать. Ну и проверять лучше на конкретное значение потом, чтобы сюрпризов не было.
Это как правило хорошего тона и хорошей привычки, чтобы потом не огрести в каком-нибудь закравшемся баге, который с виду и не предвещался ничем.

2022-09-23 20:12 UTC, Doloment commented on mods/lord/lord_classes/init.lua
> +			itemstack:add_wear(65535 / 20)
В одном месте `itemstack:add_wear(65535 / 20)`, в другом `itemstack:add_wear(65535 / 18)`, не совсем дубляж. Если и выносить, то после if-а, а в if-е определять значение переменной, на которую будет делиться число

2022-09-24 19:15 UTC, weqqr requested changes

2022-09-24 19:15 UTC, weqqr commented on mods/lord/lord_classes/init.lua
> +		end
А что механика отмычек делает в `lord_classes`?

2022-09-24 19:15 UTC, weqqr commented on mods/_lott/lottblocks/chests.lua
> +			local opened, failed_race = races.race_stuff_opener(owner_race, player, itemstack)
Название не очень, может лучше `expected_race`? И `races.can_open_stuff()`?

2022-09-24 19:15 UTC, weqqr commented on mods/_lott/lottblocks/chests.lua
> +local function register_race_chest(name, desc, tiles, owner_race, background)
Сигнатура функции поменялась, но не вижу изменённых вызовов. Так и задумано?

2022-09-24 19:49 UTC, weqqr commented on mods/lord/lord_classes/init.lua
> +	end
Это должен быть `assert`

2022-09-25 07:15 UTC, weqqr approved these changes

2022-09-25 15:40 UTC, merged