Создание основного кода
lord-server/lord pull request #822
Opened 2022-11-11 15:07 UTC by VanicGame

**Описание PR:**

Добавляет рождественнскую ель и генератор айтемов к ней.

Планируется добавить:
- ABM, при котором ель будет генерировать у себя подарки (возможно генератор удалится)
- Параметр в конфиг, по которому будет работать ABM

**Рекомендации к тесту:**

пока ничего

**Дополнительная информация:**

Комментарий к редактированию функции в ABM: если инвентарь сундука больше, чем число генерируемых айтемов (от 3 до 12), то образуется бесконечный цикл. Это было исправлено.

2022-12-13 20:07 UTC, Doloment commented on mods/lord/lord_blocks/christmas_tree.lua
> +			local target_date = string.split(minetest.settings:get("lord_christmas_data"))
Название настройки может вводить в заблуждение из-за слова data

2022-12-13 20:20 UTC, Doloment requested changes

2022-12-13 20:20 UTC, Doloment commented on mods/lord/lord_blocks/christmas_tree.lua
> +			print(date)
Debug-строчка осталась

2022-12-13 20:20 UTC, Doloment commented on mods/lord/lord_blocks/christmas_tree.lua
> +			"lord_blocks:christmas_decorations"},}
Страшна... Я конечно понимаю, что это вроде как-бы может быть нормой, но я бы растянул строчки. Надо послушать чо скажут остальные

2022-12-13 20:20 UTC, Doloment commented on mods/lord/lord_blocks/christmas_tree.lua
> +				(tonumber(target_date[4]) <= date.min) then
Тоже немного путает. Я бы сделал `date.month >= tonumber(target_date[1])` и т. д.

2022-12-13 20:26 UTC, Doloment commented
Я так понял, что ограничений на количество подарков для одного игрока нет?
И еще (чисто по коду) мне показалось, что елка будет бесконечно и без остановки генерить подарки.

2022-12-14 04:17 UTC, VanicGame commented
> Я так понял, что ограничений на количество подарков для одного игрока нет?
> И еще (чисто по коду) мне показалось, что елка будет бесконечно и без остановки генерить подарки.

Сколько подарков напишешь, столько он и выдаст. ABM завязан на christmas_tree, после генерации подарков ставится christmas_tree_with_gifts

2022-12-14 15:14 UTC, alek13 requested changes

2022-12-14 15:14 UTC, alek13 commented on mods/lord/lord_blocks/christmas_tree.lua
> +			local date = os.date("*t")
подумай над использованием названия `now` вместо `date`

2022-12-14 15:14 UTC, alek13 commented on mods/lord/lord_blocks/christmas_tree.lua
> +local gifts = string.split(minetest.settings:get("lord_christmas_gifts"))
сами конфиги (оба параметра) тоже нужно поменять и прописать:
 - для тестового в `minetest.conf.test`
 - для боевого в `minetest.conf.prod`
 
см. [Изменение конфигов](https://github.com/lord-server/lord/blob/dev/development.md#%D0%98%D0%B7%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%BE%D0%B2). Наши в конце файла.

2022-12-14 15:14 UTC, alek13 commented on mods/lord/lord_blocks/christmas_tree.lua
> +minetest.register_craft({
я может что-то пропустил, но что-то не нашёл крафтов для `christmas_decorations` и `christmas_tree_no_decorations`

2022-12-15 20:09 UTC, alek13 commented on minetest.conf.prod
> +christmas_tree_gifts = lottores:pearl 12,lottfarming:salad 3,lottpotion:cider 5,lottother:dwarf_ring
сразу тут отпишу: `lottores:pearl 12` точно не стоит.
остальное пока не смотрел

2022-12-20 16:06 UTC, alek13 commented on mods/lord/christmas/init.lua
> +	local spos = pos.x .. "," .. pos.y .. "," .. pos.z
`minetest.pos_to_string()`.
переменную чуть понятнее бы назвать, хотя бы `pos_str`

2022-12-20 16:10 UTC, alek13 commented on mods/lord/christmas/init.lua
> +local nodebox = {
`tree_nodebox` более понятно

2022-12-20 16:12 UTC, alek13 commented on mods/lord/christmas/init.lua
> +local function get_formspec(pos)
doc-block

2022-12-20 16:12 UTC, alek13 commented on mods/lord/christmas/init.lua
> +local function register_christmas_tree(def)
doc-block.

все внутренности лучше вынести в отдельный файл, функцию регистрации оттуда return'ить.
ну и прихватить туда всё, что относится к ней.

2022-12-20 16:12 UTC, alek13 commented on mods/lord/christmas/init.lua
> +	local function gen_gifts(pos)
doc-block

2022-12-20 16:22 UTC, alek13 commented on mods/lord/christmas/init.lua
> +		on_construct = function(pos, node, active_object_count, active_object_count_wider)
это обработчик думаю стоит вынести в отдельную ф-цию и дполнить doc-block'ом

2022-12-20 16:28 UTC, alek13 commented on minetest.conf.prod
> +christmas_tree_gifts = lottfarming:salad 23,lottpotion:cider 23,lottother:blue_gem_ring,lottfarming:cookie_cracker 23,default:coal_lump 23,default:apple 23,lottfarming:carrot_item 23,lottmobs:meat 23
ну про кольцо уже говорили, его не стоит добавлять.
кстати, песок появится.

2022-12-20 16:30 UTC, alek13 commented on mods/lord/christmas/init.lua
> +	local function gen_gifts(pos)
думаю не стоит нагромождать вложенность и вынести на уровень выше, -- когда уже в отдельном файле будет

2022-12-20 16:32 UTC, alek13 commented on mods/lord/lord_blocks/locale/lord_blocks.ru.tr
> +Christmas Tree=Новогодняя Ель
оставлю тут как напоминалку, что остались првки в `lord_blocks`

2022-12-20 16:52 UTC, closed without merging