Closes #980. Fix fences connection. Add hardwood fences
lord-server/lord pull request #981
Opened 2023-02-04 21:28 UTC by Doloment

![image](https://user-images.githubusercontent.com/22934348/216790232-107e30b3-3a55-49bd-a155-966acce77552.png)
![image](https://user-images.githubusercontent.com/22934348/216790246-936db882-6454-487b-b9f5-70f58f085d9b.png)

2023-02-04 21:32 UTC, alek13 commented on mods/lord/lord_homedecor/building_blocks.lua
> +default.register_fence("lord_homedecor:fence_hardwood", {
все заборы у нас в другом месте регаются ведь ?
если возможно и не особо накладно, то лучше заборы из твёрдой тоже там регать

2023-02-04 21:42 UTC, Doloment commented on mods/lord/lord_homedecor/building_blocks.lua
> +default.register_fence("lord_homedecor:fence_hardwood", {
я могу переместить в один файл, но не регистрировать функцией `lottblocks.register_wooden_stuff()`, т.к. там еще полно всякого регистрируется помимо заборов

2023-02-04 21:45 UTC, Doloment commented on mods/lord/lord_homedecor/building_blocks.lua
> +default.register_fence("lord_homedecor:fence_hardwood", {
Если перемещаю, давать имя `lottblocks` или оставить `lord_homdecor`?

2023-02-04 22:09 UTC, alek13 commented on mods/lord/lord_homedecor/building_blocks.lua
> +default.register_fence("lord_homedecor:fence_hardwood", {
обсудили:
 - исключаем люки/двери
 - улетает в `lottblocks`

2023-02-05 02:05 UTC, alek13 requested changes

2023-02-05 02:05 UTC, alek13 commented on mods/lord/lottblocks/wooden_stuff.lua
> -
случайно?

2023-02-05 02:05 UTC, alek13 commented on mods/lord/lottblocks/wooden_stuff.lua
> +		sounds = default.node_sound_wood_defaults(),
отступ

2023-02-05 02:05 UTC, alek13 commented on mods/lord/lottblocks/wooden_stuff.lua
>  		local door_uv_texture        = "lottblocks_door_" .. name .. "_uv.png"
тут отступы поплыли, видать ещё раньше

2023-02-05 02:08 UTC, alek13 commented on mods/lord/lottblocks/wooden_stuff.lua
> +		sounds = default.node_sound_wood_defaults(),
тоже отступ не тот (перед `=`)

2023-02-05 02:09 UTC, Doloment commented on mods/lord/lottblocks/wooden_stuff.lua
>  		local door_uv_texture        = "lottblocks_door_" .. name .. "_uv.png"
Я бы вообще от этих выравниваний отказался нафиг

2023-02-05 02:16 UTC, alek13 approved these changes

2023-02-05 02:16 UTC, alek13 commented on mods/lord/lottblocks/wooden_stuff.lua
>  		local door_uv_texture        = "lottblocks_door_" .. name .. "_uv.png"
ну сорян, мы их приняли, когда code-style обсуждали

2023-02-05 02:16 UTC, merged

2023-02-05 02:16 UTC, Doloment commented on mods/lord/lottblocks/wooden_stuff.lua
>  		local door_uv_texture        = "lottblocks_door_" .. name .. "_uv.png"
а, да? чот не помню...